apply plugin: 'com.android.library'
apply plugin: 'maven-publish'

group = PROJ_GROUP
version = PROJ_VERSION

android {
    namespace 'com.tencent.mars'
    compileSdk 35
    ndkVersion '28.2.13676358'

    defaultConfig {
        minSdk 21
        targetSdk 35

        ndk {
            abiFilters "armeabi-v7a", "arm64-v8a", "x86_64"
        }

        externalNativeBuild {
            cmake {
                arguments "-DANDROID_STL=c++_shared"
                targets "marsxlog"
            }
        }
    }

    sourceSets {
        main {
            java {
                srcDir "src/main/java"
            }
            jni {
                srcDir "src/main/jni"
            }
            jniLibs {
                srcDir "libs"
            }
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    externalNativeBuild {
        cmake {
            path file('CMakeLists.txt')
            version '3.22.1'
        }
    }

    publishing {
        singleVariant('release') {
            withSourcesJar()
        }
    }

    buildTypes {
        release {
            proguardFile 'proguard-rules.pro'
        }
    }
}

publishing {
    publications {
        release(MavenPublication) {
            groupId = PROJ_GROUP
            artifactId = PROJ_ARTIFACTID
            version = PROJ_VERSION

            afterEvaluate {
                from components.release
            }
        }
    }
}
